[Variables]

; Refresh the skin after updating these settings!


; DISPLAY
; =======

Bands=48
; Number of horizontal characters

Levels=24
; Number of vertical characters

FontSize=20
FontColor=161,186,220,255

CharacterWidth=1.525
; Adjust this if your chosen symbol is trimmed at the skin boundaries

FontFace=Symbola
; Must be a font that supports emojis


; AUDIO
; =====

Sensitivity=32
; Increase this if the spectrum is not visible enough

FFTAttack=350
FFTDecay=350
; Decrease for faster response, increase for slower response
; http://docs.rainmeter.net/manual-beta/plugins/audiolevel#FFTAttack

FFTSize=2048
FFTOverlap=(#FFTSize#/2)
FreqMin=40
FreqMax=16000
Port=Output
; Additional audio settings
; http://docs.rainmeter.net/manual-beta/plugins/audiolevel#FFTOptions
