[MeterString18-1]
Meter=String
MeterStyle=MeterString

[MeterString18-2]
Meter=String
MeterStyle=MeterString

[MeterString18-3]
Meter=String
MeterStyle=MeterString

[MeterString18-4]
Meter=String
MeterStyle=MeterString

[MeterString18-5]
Meter=String
MeterStyle=MeterString

[MeterString18-6]
Meter=String
MeterStyle=MeterString

[MeterString18-7]
Meter=String
MeterStyle=MeterString

[MeterString18-8]
Meter=String
MeterStyle=MeterString

[MeterString18-9]
Meter=String
MeterStyle=MeterString

[MeterString18-10]
Meter=String
MeterStyle=MeterString

[MeterString18-11]
Meter=String
MeterStyle=MeterString

[MeterString18-12]
Meter=String
MeterStyle=MeterString

[MeterString18-13]
Meter=String
MeterStyle=MeterString

[MeterString18-14]
Meter=String
MeterStyle=MeterString

[MeterString18-15]
Meter=String
MeterStyle=MeterString

[MeterString18-16]
Meter=String
MeterStyle=MeterString

[MeterString18-17]
Meter=String
MeterStyle=MeterString

[MeterString18-18]
Meter=String
MeterStyle=MeterString

[MeterString18-19]
Meter=String
MeterStyle=MeterString

[MeterString18-20]
Meter=String
MeterStyle=MeterString

[MeterString18-21]
Meter=String
MeterStyle=MeterString

[MeterString18-22]
Meter=String
MeterStyle=MeterString

[MeterString18-23]
Meter=String
MeterStyle=MeterString

[MeterString18-24]
Meter=String
MeterStyle=MeterString