[MeterString27-1]
Meter=String
MeterStyle=MeterString

[MeterString27-2]
Meter=String
MeterStyle=MeterString

[MeterString27-3]
Meter=String
MeterStyle=MeterString

[MeterString27-4]
Meter=String
MeterStyle=MeterString

[MeterString27-5]
Meter=String
MeterStyle=MeterString

[MeterString27-6]
Meter=String
MeterStyle=MeterString

[MeterString27-7]
Meter=String
MeterStyle=MeterString

[MeterString27-8]
Meter=String
MeterStyle=MeterString

[MeterString27-9]
Meter=String
MeterStyle=MeterString

[MeterString27-10]
Meter=String
MeterStyle=MeterString

[MeterString27-11]
Meter=String
MeterStyle=MeterString

[MeterString27-12]
Meter=String
MeterStyle=MeterString

[MeterString27-13]
Meter=String
MeterStyle=MeterString

[MeterString27-14]
Meter=String
MeterStyle=MeterString

[MeterString27-15]
Meter=String
MeterStyle=MeterString

[MeterString27-16]
Meter=String
MeterStyle=MeterString

[MeterString27-17]
Meter=String
MeterStyle=MeterString

[MeterString27-18]
Meter=String
MeterStyle=MeterString

[MeterString27-19]
Meter=String
MeterStyle=MeterString

[MeterString27-20]
Meter=String
MeterStyle=MeterString

[MeterString27-21]
Meter=String
MeterStyle=MeterString

[MeterString27-22]
Meter=String
MeterStyle=MeterString

[MeterString27-23]
Meter=String
MeterStyle=MeterString

[MeterString27-24]
Meter=String
MeterStyle=MeterString