[MeterString36-1]
Meter=String
MeterStyle=MeterString

[MeterString36-2]
Meter=String
MeterStyle=MeterString

[MeterString36-3]
Meter=String
MeterStyle=MeterString

[MeterString36-4]
Meter=String
MeterStyle=MeterString

[MeterString36-5]
Meter=String
MeterStyle=MeterString

[MeterString36-6]
Meter=String
MeterStyle=MeterString

[MeterString36-7]
Meter=String
MeterStyle=MeterString

[MeterString36-8]
Meter=String
MeterStyle=MeterString

[MeterString36-9]
Meter=String
MeterStyle=MeterString

[MeterString36-10]
Meter=String
MeterStyle=MeterString

[MeterString36-11]
Meter=String
MeterStyle=MeterString

[MeterString36-12]
Meter=String
MeterStyle=MeterString

[MeterString36-13]
Meter=String
MeterStyle=MeterString

[MeterString36-14]
Meter=String
MeterStyle=MeterString

[MeterString36-15]
Meter=String
MeterStyle=MeterString

[MeterString36-16]
Meter=String
MeterStyle=MeterString

[MeterString36-17]
Meter=String
MeterStyle=MeterString

[MeterString36-18]
Meter=String
MeterStyle=MeterString

[MeterString36-19]
Meter=String
MeterStyle=MeterString

[MeterString36-20]
Meter=String
MeterStyle=MeterString

[MeterString36-21]
Meter=String
MeterStyle=MeterString

[MeterString36-22]
Meter=String
MeterStyle=MeterString

[MeterString36-23]
Meter=String
MeterStyle=MeterString

[MeterString36-24]
Meter=String
MeterStyle=MeterString