[MeterString24-1]
Meter=String
MeterStyle=MeterString

[MeterString24-2]
Meter=String
MeterStyle=MeterString

[MeterString24-3]
Meter=String
MeterStyle=MeterString

[MeterString24-4]
Meter=String
MeterStyle=MeterString

[MeterString24-5]
Meter=String
MeterStyle=MeterString

[MeterString24-6]
Meter=String
MeterStyle=MeterString

[MeterString24-7]
Meter=String
MeterStyle=MeterString

[MeterString24-8]
Meter=String
MeterStyle=MeterString

[MeterString24-9]
Meter=String
MeterStyle=MeterString

[MeterString24-10]
Meter=String
MeterStyle=MeterString

[MeterString24-11]
Meter=String
MeterStyle=MeterString

[MeterString24-12]
Meter=String
MeterStyle=MeterString

[MeterString24-13]
Meter=String
MeterStyle=MeterString

[MeterString24-14]
Meter=String
MeterStyle=MeterString

[MeterString24-15]
Meter=String
MeterStyle=MeterString

[MeterString24-16]
Meter=String
MeterStyle=MeterString

[MeterString24-17]
Meter=String
MeterStyle=MeterString

[MeterString24-18]
Meter=String
MeterStyle=MeterString

[MeterString24-19]
Meter=String
MeterStyle=MeterString

[MeterString24-20]
Meter=String
MeterStyle=MeterString

[MeterString24-21]
Meter=String
MeterStyle=MeterString

[MeterString24-22]
Meter=String
MeterStyle=MeterString

[MeterString24-23]
Meter=String
MeterStyle=MeterString

[MeterString24-24]
Meter=String
MeterStyle=MeterString