[MeterString39-1]
Meter=String
MeterStyle=MeterString

[MeterString39-2]
Meter=String
MeterStyle=MeterString

[MeterString39-3]
Meter=String
MeterStyle=MeterString

[MeterString39-4]
Meter=String
MeterStyle=MeterString

[MeterString39-5]
Meter=String
MeterStyle=MeterString

[MeterString39-6]
Meter=String
MeterStyle=MeterString

[MeterString39-7]
Meter=String
MeterStyle=MeterString

[MeterString39-8]
Meter=String
MeterStyle=MeterString

[MeterString39-9]
Meter=String
MeterStyle=MeterString

[MeterString39-10]
Meter=String
MeterStyle=MeterString

[MeterString39-11]
Meter=String
MeterStyle=MeterString

[MeterString39-12]
Meter=String
MeterStyle=MeterString

[MeterString39-13]
Meter=String
MeterStyle=MeterString

[MeterString39-14]
Meter=String
MeterStyle=MeterString

[MeterString39-15]
Meter=String
MeterStyle=MeterString

[MeterString39-16]
Meter=String
MeterStyle=MeterString

[MeterString39-17]
Meter=String
MeterStyle=MeterString

[MeterString39-18]
Meter=String
MeterStyle=MeterString

[MeterString39-19]
Meter=String
MeterStyle=MeterString

[MeterString39-20]
Meter=String
MeterStyle=MeterString

[MeterString39-21]
Meter=String
MeterStyle=MeterString

[MeterString39-22]
Meter=String
MeterStyle=MeterString

[MeterString39-23]
Meter=String
MeterStyle=MeterString

[MeterString39-24]
Meter=String
MeterStyle=MeterString