[MeterString11-1]
Meter=String
MeterStyle=MeterString

[MeterString11-2]
Meter=String
MeterStyle=MeterString

[MeterString11-3]
Meter=String
MeterStyle=MeterString

[MeterString11-4]
Meter=String
MeterStyle=MeterString

[MeterString11-5]
Meter=String
MeterStyle=MeterString

[MeterString11-6]
Meter=String
MeterStyle=MeterString

[MeterString11-7]
Meter=String
MeterStyle=MeterString

[MeterString11-8]
Meter=String
MeterStyle=MeterString

[MeterString11-9]
Meter=String
MeterStyle=MeterString

[MeterString11-10]
Meter=String
MeterStyle=MeterString

[MeterString11-11]
Meter=String
MeterStyle=MeterString

[MeterString11-12]
Meter=String
MeterStyle=MeterString

[MeterString11-13]
Meter=String
MeterStyle=MeterString

[MeterString11-14]
Meter=String
MeterStyle=MeterString

[MeterString11-15]
Meter=String
MeterStyle=MeterString

[MeterString11-16]
Meter=String
MeterStyle=MeterString

[MeterString11-17]
Meter=String
MeterStyle=MeterString

[MeterString11-18]
Meter=String
MeterStyle=MeterString

[MeterString11-19]
Meter=String
MeterStyle=MeterString

[MeterString11-20]
Meter=String
MeterStyle=MeterString

[MeterString11-21]
Meter=String
MeterStyle=MeterString

[MeterString11-22]
Meter=String
MeterStyle=MeterString

[MeterString11-23]
Meter=String
MeterStyle=MeterString

[MeterString11-24]
Meter=String
MeterStyle=MeterString