[MeterString19-1]
Meter=String
MeterStyle=MeterString

[MeterString19-2]
Meter=String
MeterStyle=MeterString

[MeterString19-3]
Meter=String
MeterStyle=MeterString

[MeterString19-4]
Meter=String
MeterStyle=MeterString

[MeterString19-5]
Meter=String
MeterStyle=MeterString

[MeterString19-6]
Meter=String
MeterStyle=MeterString

[MeterString19-7]
Meter=String
MeterStyle=MeterString

[MeterString19-8]
Meter=String
MeterStyle=MeterString

[MeterString19-9]
Meter=String
MeterStyle=MeterString

[MeterString19-10]
Meter=String
MeterStyle=MeterString

[MeterString19-11]
Meter=String
MeterStyle=MeterString

[MeterString19-12]
Meter=String
MeterStyle=MeterString

[MeterString19-13]
Meter=String
MeterStyle=MeterString

[MeterString19-14]
Meter=String
MeterStyle=MeterString

[MeterString19-15]
Meter=String
MeterStyle=MeterString

[MeterString19-16]
Meter=String
MeterStyle=MeterString

[MeterString19-17]
Meter=String
MeterStyle=MeterString

[MeterString19-18]
Meter=String
MeterStyle=MeterString

[MeterString19-19]
Meter=String
MeterStyle=MeterString

[MeterString19-20]
Meter=String
MeterStyle=MeterString

[MeterString19-21]
Meter=String
MeterStyle=MeterString

[MeterString19-22]
Meter=String
MeterStyle=MeterString

[MeterString19-23]
Meter=String
MeterStyle=MeterString

[MeterString19-24]
Meter=String
MeterStyle=MeterString