[MeterString12-1]
Meter=String
MeterStyle=MeterString

[MeterString12-2]
Meter=String
MeterStyle=MeterString

[MeterString12-3]
Meter=String
MeterStyle=MeterString

[MeterString12-4]
Meter=String
MeterStyle=MeterString

[MeterString12-5]
Meter=String
MeterStyle=MeterString

[MeterString12-6]
Meter=String
MeterStyle=MeterString

[MeterString12-7]
Meter=String
MeterStyle=MeterString

[MeterString12-8]
Meter=String
MeterStyle=MeterString

[MeterString12-9]
Meter=String
MeterStyle=MeterString

[MeterString12-10]
Meter=String
MeterStyle=MeterString

[MeterString12-11]
Meter=String
MeterStyle=MeterString

[MeterString12-12]
Meter=String
MeterStyle=MeterString

[MeterString12-13]
Meter=String
MeterStyle=MeterString

[MeterString12-14]
Meter=String
MeterStyle=MeterString

[MeterString12-15]
Meter=String
MeterStyle=MeterString

[MeterString12-16]
Meter=String
MeterStyle=MeterString

[MeterString12-17]
Meter=String
MeterStyle=MeterString

[MeterString12-18]
Meter=String
MeterStyle=MeterString

[MeterString12-19]
Meter=String
MeterStyle=MeterString

[MeterString12-20]
Meter=String
MeterStyle=MeterString

[MeterString12-21]
Meter=String
MeterStyle=MeterString

[MeterString12-22]
Meter=String
MeterStyle=MeterString

[MeterString12-23]
Meter=String
MeterStyle=MeterString

[MeterString12-24]
Meter=String
MeterStyle=MeterString