[MeterString8-1]
Meter=String
MeterStyle=MeterString

[MeterString8-2]
Meter=String
MeterStyle=MeterString

[MeterString8-3]
Meter=String
MeterStyle=MeterString

[MeterString8-4]
Meter=String
MeterStyle=MeterString

[MeterString8-5]
Meter=String
MeterStyle=MeterString

[MeterString8-6]
Meter=String
MeterStyle=MeterString

[MeterString8-7]
Meter=String
MeterStyle=MeterString

[MeterString8-8]
Meter=String
MeterStyle=MeterString

[MeterString8-9]
Meter=String
MeterStyle=MeterString

[MeterString8-10]
Meter=String
MeterStyle=MeterString

[MeterString8-11]
Meter=String
MeterStyle=MeterString

[MeterString8-12]
Meter=String
MeterStyle=MeterString

[MeterString8-13]
Meter=String
MeterStyle=MeterString

[MeterString8-14]
Meter=String
MeterStyle=MeterString

[MeterString8-15]
Meter=String
MeterStyle=MeterString

[MeterString8-16]
Meter=String
MeterStyle=MeterString

[MeterString8-17]
Meter=String
MeterStyle=MeterString

[MeterString8-18]
Meter=String
MeterStyle=MeterString

[MeterString8-19]
Meter=String
MeterStyle=MeterString

[MeterString8-20]
Meter=String
MeterStyle=MeterString

[MeterString8-21]
Meter=String
MeterStyle=MeterString

[MeterString8-22]
Meter=String
MeterStyle=MeterString

[MeterString8-23]
Meter=String
MeterStyle=MeterString

[MeterString8-24]
Meter=String
MeterStyle=MeterString