[MeterString33-1]
Meter=String
MeterStyle=MeterString

[MeterString33-2]
Meter=String
MeterStyle=MeterString

[MeterString33-3]
Meter=String
MeterStyle=MeterString

[MeterString33-4]
Meter=String
MeterStyle=MeterString

[MeterString33-5]
Meter=String
MeterStyle=MeterString

[MeterString33-6]
Meter=String
MeterStyle=MeterString

[MeterString33-7]
Meter=String
MeterStyle=MeterString

[MeterString33-8]
Meter=String
MeterStyle=MeterString

[MeterString33-9]
Meter=String
MeterStyle=MeterString

[MeterString33-10]
Meter=String
MeterStyle=MeterString

[MeterString33-11]
Meter=String
MeterStyle=MeterString

[MeterString33-12]
Meter=String
MeterStyle=MeterString

[MeterString33-13]
Meter=String
MeterStyle=MeterString

[MeterString33-14]
Meter=String
MeterStyle=MeterString

[MeterString33-15]
Meter=String
MeterStyle=MeterString

[MeterString33-16]
Meter=String
MeterStyle=MeterString

[MeterString33-17]
Meter=String
MeterStyle=MeterString

[MeterString33-18]
Meter=String
MeterStyle=MeterString

[MeterString33-19]
Meter=String
MeterStyle=MeterString

[MeterString33-20]
Meter=String
MeterStyle=MeterString

[MeterString33-21]
Meter=String
MeterStyle=MeterString

[MeterString33-22]
Meter=String
MeterStyle=MeterString

[MeterString33-23]
Meter=String
MeterStyle=MeterString

[MeterString33-24]
Meter=String
MeterStyle=MeterString