[MeterString43-1]
Meter=String
MeterStyle=MeterString

[MeterString43-2]
Meter=String
MeterStyle=MeterString

[MeterString43-3]
Meter=String
MeterStyle=MeterString

[MeterString43-4]
Meter=String
MeterStyle=MeterString

[MeterString43-5]
Meter=String
MeterStyle=MeterString

[MeterString43-6]
Meter=String
MeterStyle=MeterString

[MeterString43-7]
Meter=String
MeterStyle=MeterString

[MeterString43-8]
Meter=String
MeterStyle=MeterString

[MeterString43-9]
Meter=String
MeterStyle=MeterString

[MeterString43-10]
Meter=String
MeterStyle=MeterString

[MeterString43-11]
Meter=String
MeterStyle=MeterString

[MeterString43-12]
Meter=String
MeterStyle=MeterString

[MeterString43-13]
Meter=String
MeterStyle=MeterString

[MeterString43-14]
Meter=String
MeterStyle=MeterString

[MeterString43-15]
Meter=String
MeterStyle=MeterString

[MeterString43-16]
Meter=String
MeterStyle=MeterString

[MeterString43-17]
Meter=String
MeterStyle=MeterString

[MeterString43-18]
Meter=String
MeterStyle=MeterString

[MeterString43-19]
Meter=String
MeterStyle=MeterString

[MeterString43-20]
Meter=String
MeterStyle=MeterString

[MeterString43-21]
Meter=String
MeterStyle=MeterString

[MeterString43-22]
Meter=String
MeterStyle=MeterString

[MeterString43-23]
Meter=String
MeterStyle=MeterString

[MeterString43-24]
Meter=String
MeterStyle=MeterString