[MeterString17-1]
Meter=String
MeterStyle=MeterString

[MeterString17-2]
Meter=String
MeterStyle=MeterString

[MeterString17-3]
Meter=String
MeterStyle=MeterString

[MeterString17-4]
Meter=String
MeterStyle=MeterString

[MeterString17-5]
Meter=String
MeterStyle=MeterString

[MeterString17-6]
Meter=String
MeterStyle=MeterString

[MeterString17-7]
Meter=String
MeterStyle=MeterString

[MeterString17-8]
Meter=String
MeterStyle=MeterString

[MeterString17-9]
Meter=String
MeterStyle=MeterString

[MeterString17-10]
Meter=String
MeterStyle=MeterString

[MeterString17-11]
Meter=String
MeterStyle=MeterString

[MeterString17-12]
Meter=String
MeterStyle=MeterString

[MeterString17-13]
Meter=String
MeterStyle=MeterString

[MeterString17-14]
Meter=String
MeterStyle=MeterString

[MeterString17-15]
Meter=String
MeterStyle=MeterString

[MeterString17-16]
Meter=String
MeterStyle=MeterString

[MeterString17-17]
Meter=String
MeterStyle=MeterString

[MeterString17-18]
Meter=String
MeterStyle=MeterString

[MeterString17-19]
Meter=String
MeterStyle=MeterString

[MeterString17-20]
Meter=String
MeterStyle=MeterString

[MeterString17-21]
Meter=String
MeterStyle=MeterString

[MeterString17-22]
Meter=String
MeterStyle=MeterString

[MeterString17-23]
Meter=String
MeterStyle=MeterString

[MeterString17-24]
Meter=String
MeterStyle=MeterString