[MeterString21-1]
Meter=String
MeterStyle=MeterString

[MeterString21-2]
Meter=String
MeterStyle=MeterString

[MeterString21-3]
Meter=String
MeterStyle=MeterString

[MeterString21-4]
Meter=String
MeterStyle=MeterString

[MeterString21-5]
Meter=String
MeterStyle=MeterString

[MeterString21-6]
Meter=String
MeterStyle=MeterString

[MeterString21-7]
Meter=String
MeterStyle=MeterString

[MeterString21-8]
Meter=String
MeterStyle=MeterString

[MeterString21-9]
Meter=String
MeterStyle=MeterString

[MeterString21-10]
Meter=String
MeterStyle=MeterString

[MeterString21-11]
Meter=String
MeterStyle=MeterString

[MeterString21-12]
Meter=String
MeterStyle=MeterString

[MeterString21-13]
Meter=String
MeterStyle=MeterString

[MeterString21-14]
Meter=String
MeterStyle=MeterString

[MeterString21-15]
Meter=String
MeterStyle=MeterString

[MeterString21-16]
Meter=String
MeterStyle=MeterString

[MeterString21-17]
Meter=String
MeterStyle=MeterString

[MeterString21-18]
Meter=String
MeterStyle=MeterString

[MeterString21-19]
Meter=String
MeterStyle=MeterString

[MeterString21-20]
Meter=String
MeterStyle=MeterString

[MeterString21-21]
Meter=String
MeterStyle=MeterString

[MeterString21-22]
Meter=String
MeterStyle=MeterString

[MeterString21-23]
Meter=String
MeterStyle=MeterString

[MeterString21-24]
Meter=String
MeterStyle=MeterString