[MeterString16-1]
Meter=String
MeterStyle=MeterString

[MeterString16-2]
Meter=String
MeterStyle=MeterString

[MeterString16-3]
Meter=String
MeterStyle=MeterString

[MeterString16-4]
Meter=String
MeterStyle=MeterString

[MeterString16-5]
Meter=String
MeterStyle=MeterString

[MeterString16-6]
Meter=String
MeterStyle=MeterString

[MeterString16-7]
Meter=String
MeterStyle=MeterString

[MeterString16-8]
Meter=String
MeterStyle=MeterString

[MeterString16-9]
Meter=String
MeterStyle=MeterString

[MeterString16-10]
Meter=String
MeterStyle=MeterString

[MeterString16-11]
Meter=String
MeterStyle=MeterString

[MeterString16-12]
Meter=String
MeterStyle=MeterString

[MeterString16-13]
Meter=String
MeterStyle=MeterString

[MeterString16-14]
Meter=String
MeterStyle=MeterString

[MeterString16-15]
Meter=String
MeterStyle=MeterString

[MeterString16-16]
Meter=String
MeterStyle=MeterString

[MeterString16-17]
Meter=String
MeterStyle=MeterString

[MeterString16-18]
Meter=String
MeterStyle=MeterString

[MeterString16-19]
Meter=String
MeterStyle=MeterString

[MeterString16-20]
Meter=String
MeterStyle=MeterString

[MeterString16-21]
Meter=String
MeterStyle=MeterString

[MeterString16-22]
Meter=String
MeterStyle=MeterString

[MeterString16-23]
Meter=String
MeterStyle=MeterString

[MeterString16-24]
Meter=String
MeterStyle=MeterString