[MeterString2-1]
Meter=String
MeterStyle=MeterString

[MeterString2-2]
Meter=String
MeterStyle=MeterString

[MeterString2-3]
Meter=String
MeterStyle=MeterString

[MeterString2-4]
Meter=String
MeterStyle=MeterString

[MeterString2-5]
Meter=String
MeterStyle=MeterString

[MeterString2-6]
Meter=String
MeterStyle=MeterString

[MeterString2-7]
Meter=String
MeterStyle=MeterString

[MeterString2-8]
Meter=String
MeterStyle=MeterString

[MeterString2-9]
Meter=String
MeterStyle=MeterString

[MeterString2-10]
Meter=String
MeterStyle=MeterString

[MeterString2-11]
Meter=String
MeterStyle=MeterString

[MeterString2-12]
Meter=String
MeterStyle=MeterString

[MeterString2-13]
Meter=String
MeterStyle=MeterString

[MeterString2-14]
Meter=String
MeterStyle=MeterString

[MeterString2-15]
Meter=String
MeterStyle=MeterString

[MeterString2-16]
Meter=String
MeterStyle=MeterString

[MeterString2-17]
Meter=String
MeterStyle=MeterString

[MeterString2-18]
Meter=String
MeterStyle=MeterString

[MeterString2-19]
Meter=String
MeterStyle=MeterString

[MeterString2-20]
Meter=String
MeterStyle=MeterString

[MeterString2-21]
Meter=String
MeterStyle=MeterString

[MeterString2-22]
Meter=String
MeterStyle=MeterString

[MeterString2-23]
Meter=String
MeterStyle=MeterString

[MeterString2-24]
Meter=String
MeterStyle=MeterString