[MeterString31-1]
Meter=String
MeterStyle=MeterString

[MeterString31-2]
Meter=String
MeterStyle=MeterString

[MeterString31-3]
Meter=String
MeterStyle=MeterString

[MeterString31-4]
Meter=String
MeterStyle=MeterString

[MeterString31-5]
Meter=String
MeterStyle=MeterString

[MeterString31-6]
Meter=String
MeterStyle=MeterString

[MeterString31-7]
Meter=String
MeterStyle=MeterString

[MeterString31-8]
Meter=String
MeterStyle=MeterString

[MeterString31-9]
Meter=String
MeterStyle=MeterString

[MeterString31-10]
Meter=String
MeterStyle=MeterString

[MeterString31-11]
Meter=String
MeterStyle=MeterString

[MeterString31-12]
Meter=String
MeterStyle=MeterString

[MeterString31-13]
Meter=String
MeterStyle=MeterString

[MeterString31-14]
Meter=String
MeterStyle=MeterString

[MeterString31-15]
Meter=String
MeterStyle=MeterString

[MeterString31-16]
Meter=String
MeterStyle=MeterString

[MeterString31-17]
Meter=String
MeterStyle=MeterString

[MeterString31-18]
Meter=String
MeterStyle=MeterString

[MeterString31-19]
Meter=String
MeterStyle=MeterString

[MeterString31-20]
Meter=String
MeterStyle=MeterString

[MeterString31-21]
Meter=String
MeterStyle=MeterString

[MeterString31-22]
Meter=String
MeterStyle=MeterString

[MeterString31-23]
Meter=String
MeterStyle=MeterString

[MeterString31-24]
Meter=String
MeterStyle=MeterString