[MeterString28-1]
Meter=String
MeterStyle=MeterString

[MeterString28-2]
Meter=String
MeterStyle=MeterString

[MeterString28-3]
Meter=String
MeterStyle=MeterString

[MeterString28-4]
Meter=String
MeterStyle=MeterString

[MeterString28-5]
Meter=String
MeterStyle=MeterString

[MeterString28-6]
Meter=String
MeterStyle=MeterString

[MeterString28-7]
Meter=String
MeterStyle=MeterString

[MeterString28-8]
Meter=String
MeterStyle=MeterString

[MeterString28-9]
Meter=String
MeterStyle=MeterString

[MeterString28-10]
Meter=String
MeterStyle=MeterString

[MeterString28-11]
Meter=String
MeterStyle=MeterString

[MeterString28-12]
Meter=String
MeterStyle=MeterString

[MeterString28-13]
Meter=String
MeterStyle=MeterString

[MeterString28-14]
Meter=String
MeterStyle=MeterString

[MeterString28-15]
Meter=String
MeterStyle=MeterString

[MeterString28-16]
Meter=String
MeterStyle=MeterString

[MeterString28-17]
Meter=String
MeterStyle=MeterString

[MeterString28-18]
Meter=String
MeterStyle=MeterString

[MeterString28-19]
Meter=String
MeterStyle=MeterString

[MeterString28-20]
Meter=String
MeterStyle=MeterString

[MeterString28-21]
Meter=String
MeterStyle=MeterString

[MeterString28-22]
Meter=String
MeterStyle=MeterString

[MeterString28-23]
Meter=String
MeterStyle=MeterString

[MeterString28-24]
Meter=String
MeterStyle=MeterString