[MeterString26-1]
Meter=String
MeterStyle=MeterString

[MeterString26-2]
Meter=String
MeterStyle=MeterString

[MeterString26-3]
Meter=String
MeterStyle=MeterString

[MeterString26-4]
Meter=String
MeterStyle=MeterString

[MeterString26-5]
Meter=String
MeterStyle=MeterString

[MeterString26-6]
Meter=String
MeterStyle=MeterString

[MeterString26-7]
Meter=String
MeterStyle=MeterString

[MeterString26-8]
Meter=String
MeterStyle=MeterString

[MeterString26-9]
Meter=String
MeterStyle=MeterString

[MeterString26-10]
Meter=String
MeterStyle=MeterString

[MeterString26-11]
Meter=String
MeterStyle=MeterString

[MeterString26-12]
Meter=String
MeterStyle=MeterString

[MeterString26-13]
Meter=String
MeterStyle=MeterString

[MeterString26-14]
Meter=String
MeterStyle=MeterString

[MeterString26-15]
Meter=String
MeterStyle=MeterString

[MeterString26-16]
Meter=String
MeterStyle=MeterString

[MeterString26-17]
Meter=String
MeterStyle=MeterString

[MeterString26-18]
Meter=String
MeterStyle=MeterString

[MeterString26-19]
Meter=String
MeterStyle=MeterString

[MeterString26-20]
Meter=String
MeterStyle=MeterString

[MeterString26-21]
Meter=String
MeterStyle=MeterString

[MeterString26-22]
Meter=String
MeterStyle=MeterString

[MeterString26-23]
Meter=String
MeterStyle=MeterString

[MeterString26-24]
Meter=String
MeterStyle=MeterString