[MeterString34-1]
Meter=String
MeterStyle=MeterString

[MeterString34-2]
Meter=String
MeterStyle=MeterString

[MeterString34-3]
Meter=String
MeterStyle=MeterString

[MeterString34-4]
Meter=String
MeterStyle=MeterString

[MeterString34-5]
Meter=String
MeterStyle=MeterString

[MeterString34-6]
Meter=String
MeterStyle=MeterString

[MeterString34-7]
Meter=String
MeterStyle=MeterString

[MeterString34-8]
Meter=String
MeterStyle=MeterString

[MeterString34-9]
Meter=String
MeterStyle=MeterString

[MeterString34-10]
Meter=String
MeterStyle=MeterString

[MeterString34-11]
Meter=String
MeterStyle=MeterString

[MeterString34-12]
Meter=String
MeterStyle=MeterString

[MeterString34-13]
Meter=String
MeterStyle=MeterString

[MeterString34-14]
Meter=String
MeterStyle=MeterString

[MeterString34-15]
Meter=String
MeterStyle=MeterString

[MeterString34-16]
Meter=String
MeterStyle=MeterString

[MeterString34-17]
Meter=String
MeterStyle=MeterString

[MeterString34-18]
Meter=String
MeterStyle=MeterString

[MeterString34-19]
Meter=String
MeterStyle=MeterString

[MeterString34-20]
Meter=String
MeterStyle=MeterString

[MeterString34-21]
Meter=String
MeterStyle=MeterString

[MeterString34-22]
Meter=String
MeterStyle=MeterString

[MeterString34-23]
Meter=String
MeterStyle=MeterString

[MeterString34-24]
Meter=String
MeterStyle=MeterString