[MeterString20-1]
Meter=String
MeterStyle=MeterString

[MeterString20-2]
Meter=String
MeterStyle=MeterString

[MeterString20-3]
Meter=String
MeterStyle=MeterString

[MeterString20-4]
Meter=String
MeterStyle=MeterString

[MeterString20-5]
Meter=String
MeterStyle=MeterString

[MeterString20-6]
Meter=String
MeterStyle=MeterString

[MeterString20-7]
Meter=String
MeterStyle=MeterString

[MeterString20-8]
Meter=String
MeterStyle=MeterString

[MeterString20-9]
Meter=String
MeterStyle=MeterString

[MeterString20-10]
Meter=String
MeterStyle=MeterString

[MeterString20-11]
Meter=String
MeterStyle=MeterString

[MeterString20-12]
Meter=String
MeterStyle=MeterString

[MeterString20-13]
Meter=String
MeterStyle=MeterString

[MeterString20-14]
Meter=String
MeterStyle=MeterString

[MeterString20-15]
Meter=String
MeterStyle=MeterString

[MeterString20-16]
Meter=String
MeterStyle=MeterString

[MeterString20-17]
Meter=String
MeterStyle=MeterString

[MeterString20-18]
Meter=String
MeterStyle=MeterString

[MeterString20-19]
Meter=String
MeterStyle=MeterString

[MeterString20-20]
Meter=String
MeterStyle=MeterString

[MeterString20-21]
Meter=String
MeterStyle=MeterString

[MeterString20-22]
Meter=String
MeterStyle=MeterString

[MeterString20-23]
Meter=String
MeterStyle=MeterString

[MeterString20-24]
Meter=String
MeterStyle=MeterString