[MeterString47-1]
Meter=String
MeterStyle=MeterString

[MeterString47-2]
Meter=String
MeterStyle=MeterString

[MeterString47-3]
Meter=String
MeterStyle=MeterString

[MeterString47-4]
Meter=String
MeterStyle=MeterString

[MeterString47-5]
Meter=String
MeterStyle=MeterString

[MeterString47-6]
Meter=String
MeterStyle=MeterString

[MeterString47-7]
Meter=String
MeterStyle=MeterString

[MeterString47-8]
Meter=String
MeterStyle=MeterString

[MeterString47-9]
Meter=String
MeterStyle=MeterString

[MeterString47-10]
Meter=String
MeterStyle=MeterString

[MeterString47-11]
Meter=String
MeterStyle=MeterString

[MeterString47-12]
Meter=String
MeterStyle=MeterString

[MeterString47-13]
Meter=String
MeterStyle=MeterString

[MeterString47-14]
Meter=String
MeterStyle=MeterString

[MeterString47-15]
Meter=String
MeterStyle=MeterString

[MeterString47-16]
Meter=String
MeterStyle=MeterString

[MeterString47-17]
Meter=String
MeterStyle=MeterString

[MeterString47-18]
Meter=String
MeterStyle=MeterString

[MeterString47-19]
Meter=String
MeterStyle=MeterString

[MeterString47-20]
Meter=String
MeterStyle=MeterString

[MeterString47-21]
Meter=String
MeterStyle=MeterString

[MeterString47-22]
Meter=String
MeterStyle=MeterString

[MeterString47-23]
Meter=String
MeterStyle=MeterString

[MeterString47-24]
Meter=String
MeterStyle=MeterString