[MeterString9-1]
Meter=String
MeterStyle=MeterString

[MeterString9-2]
Meter=String
MeterStyle=MeterString

[MeterString9-3]
Meter=String
MeterStyle=MeterString

[MeterString9-4]
Meter=String
MeterStyle=MeterString

[MeterString9-5]
Meter=String
MeterStyle=MeterString

[MeterString9-6]
Meter=String
MeterStyle=MeterString

[MeterString9-7]
Meter=String
MeterStyle=MeterString

[MeterString9-8]
Meter=String
MeterStyle=MeterString

[MeterString9-9]
Meter=String
MeterStyle=MeterString

[MeterString9-10]
Meter=String
MeterStyle=MeterString

[MeterString9-11]
Meter=String
MeterStyle=MeterString

[MeterString9-12]
Meter=String
MeterStyle=MeterString

[MeterString9-13]
Meter=String
MeterStyle=MeterString

[MeterString9-14]
Meter=String
MeterStyle=MeterString

[MeterString9-15]
Meter=String
MeterStyle=MeterString

[MeterString9-16]
Meter=String
MeterStyle=MeterString

[MeterString9-17]
Meter=String
MeterStyle=MeterString

[MeterString9-18]
Meter=String
MeterStyle=MeterString

[MeterString9-19]
Meter=String
MeterStyle=MeterString

[MeterString9-20]
Meter=String
MeterStyle=MeterString

[MeterString9-21]
Meter=String
MeterStyle=MeterString

[MeterString9-22]
Meter=String
MeterStyle=MeterString

[MeterString9-23]
Meter=String
MeterStyle=MeterString

[MeterString9-24]
Meter=String
MeterStyle=MeterString