[MeterString15-1]
Meter=String
MeterStyle=MeterString

[MeterString15-2]
Meter=String
MeterStyle=MeterString

[MeterString15-3]
Meter=String
MeterStyle=MeterString

[MeterString15-4]
Meter=String
MeterStyle=MeterString

[MeterString15-5]
Meter=String
MeterStyle=MeterString

[MeterString15-6]
Meter=String
MeterStyle=MeterString

[MeterString15-7]
Meter=String
MeterStyle=MeterString

[MeterString15-8]
Meter=String
MeterStyle=MeterString

[MeterString15-9]
Meter=String
MeterStyle=MeterString

[MeterString15-10]
Meter=String
MeterStyle=MeterString

[MeterString15-11]
Meter=String
MeterStyle=MeterString

[MeterString15-12]
Meter=String
MeterStyle=MeterString

[MeterString15-13]
Meter=String
MeterStyle=MeterString

[MeterString15-14]
Meter=String
MeterStyle=MeterString

[MeterString15-15]
Meter=String
MeterStyle=MeterString

[MeterString15-16]
Meter=String
MeterStyle=MeterString

[MeterString15-17]
Meter=String
MeterStyle=MeterString

[MeterString15-18]
Meter=String
MeterStyle=MeterString

[MeterString15-19]
Meter=String
MeterStyle=MeterString

[MeterString15-20]
Meter=String
MeterStyle=MeterString

[MeterString15-21]
Meter=String
MeterStyle=MeterString

[MeterString15-22]
Meter=String
MeterStyle=MeterString

[MeterString15-23]
Meter=String
MeterStyle=MeterString

[MeterString15-24]
Meter=String
MeterStyle=MeterString