[MeterString44-1]
Meter=String
MeterStyle=MeterString

[MeterString44-2]
Meter=String
MeterStyle=MeterString

[MeterString44-3]
Meter=String
MeterStyle=MeterString

[MeterString44-4]
Meter=String
MeterStyle=MeterString

[MeterString44-5]
Meter=String
MeterStyle=MeterString

[MeterString44-6]
Meter=String
MeterStyle=MeterString

[MeterString44-7]
Meter=String
MeterStyle=MeterString

[MeterString44-8]
Meter=String
MeterStyle=MeterString

[MeterString44-9]
Meter=String
MeterStyle=MeterString

[MeterString44-10]
Meter=String
MeterStyle=MeterString

[MeterString44-11]
Meter=String
MeterStyle=MeterString

[MeterString44-12]
Meter=String
MeterStyle=MeterString

[MeterString44-13]
Meter=String
MeterStyle=MeterString

[MeterString44-14]
Meter=String
MeterStyle=MeterString

[MeterString44-15]
Meter=String
MeterStyle=MeterString

[MeterString44-16]
Meter=String
MeterStyle=MeterString

[MeterString44-17]
Meter=String
MeterStyle=MeterString

[MeterString44-18]
Meter=String
MeterStyle=MeterString

[MeterString44-19]
Meter=String
MeterStyle=MeterString

[MeterString44-20]
Meter=String
MeterStyle=MeterString

[MeterString44-21]
Meter=String
MeterStyle=MeterString

[MeterString44-22]
Meter=String
MeterStyle=MeterString

[MeterString44-23]
Meter=String
MeterStyle=MeterString

[MeterString44-24]
Meter=String
MeterStyle=MeterString