[MeterString35-1]
Meter=String
MeterStyle=MeterString

[MeterString35-2]
Meter=String
MeterStyle=MeterString

[MeterString35-3]
Meter=String
MeterStyle=MeterString

[MeterString35-4]
Meter=String
MeterStyle=MeterString

[MeterString35-5]
Meter=String
MeterStyle=MeterString

[MeterString35-6]
Meter=String
MeterStyle=MeterString

[MeterString35-7]
Meter=String
MeterStyle=MeterString

[MeterString35-8]
Meter=String
MeterStyle=MeterString

[MeterString35-9]
Meter=String
MeterStyle=MeterString

[MeterString35-10]
Meter=String
MeterStyle=MeterString

[MeterString35-11]
Meter=String
MeterStyle=MeterString

[MeterString35-12]
Meter=String
MeterStyle=MeterString

[MeterString35-13]
Meter=String
MeterStyle=MeterString

[MeterString35-14]
Meter=String
MeterStyle=MeterString

[MeterString35-15]
Meter=String
MeterStyle=MeterString

[MeterString35-16]
Meter=String
MeterStyle=MeterString

[MeterString35-17]
Meter=String
MeterStyle=MeterString

[MeterString35-18]
Meter=String
MeterStyle=MeterString

[MeterString35-19]
Meter=String
MeterStyle=MeterString

[MeterString35-20]
Meter=String
MeterStyle=MeterString

[MeterString35-21]
Meter=String
MeterStyle=MeterString

[MeterString35-22]
Meter=String
MeterStyle=MeterString

[MeterString35-23]
Meter=String
MeterStyle=MeterString

[MeterString35-24]
Meter=String
MeterStyle=MeterString