[MeterString25-1]
Meter=String
MeterStyle=MeterString

[MeterString25-2]
Meter=String
MeterStyle=MeterString

[MeterString25-3]
Meter=String
MeterStyle=MeterString

[MeterString25-4]
Meter=String
MeterStyle=MeterString

[MeterString25-5]
Meter=String
MeterStyle=MeterString

[MeterString25-6]
Meter=String
MeterStyle=MeterString

[MeterString25-7]
Meter=String
MeterStyle=MeterString

[MeterString25-8]
Meter=String
MeterStyle=MeterString

[MeterString25-9]
Meter=String
MeterStyle=MeterString

[MeterString25-10]
Meter=String
MeterStyle=MeterString

[MeterString25-11]
Meter=String
MeterStyle=MeterString

[MeterString25-12]
Meter=String
MeterStyle=MeterString

[MeterString25-13]
Meter=String
MeterStyle=MeterString

[MeterString25-14]
Meter=String
MeterStyle=MeterString

[MeterString25-15]
Meter=String
MeterStyle=MeterString

[MeterString25-16]
Meter=String
MeterStyle=MeterString

[MeterString25-17]
Meter=String
MeterStyle=MeterString

[MeterString25-18]
Meter=String
MeterStyle=MeterString

[MeterString25-19]
Meter=String
MeterStyle=MeterString

[MeterString25-20]
Meter=String
MeterStyle=MeterString

[MeterString25-21]
Meter=String
MeterStyle=MeterString

[MeterString25-22]
Meter=String
MeterStyle=MeterString

[MeterString25-23]
Meter=String
MeterStyle=MeterString

[MeterString25-24]
Meter=String
MeterStyle=MeterString