[MeterString40-1]
Meter=String
MeterStyle=MeterString

[MeterString40-2]
Meter=String
MeterStyle=MeterString

[MeterString40-3]
Meter=String
MeterStyle=MeterString

[MeterString40-4]
Meter=String
MeterStyle=MeterString

[MeterString40-5]
Meter=String
MeterStyle=MeterString

[MeterString40-6]
Meter=String
MeterStyle=MeterString

[MeterString40-7]
Meter=String
MeterStyle=MeterString

[MeterString40-8]
Meter=String
MeterStyle=MeterString

[MeterString40-9]
Meter=String
MeterStyle=MeterString

[MeterString40-10]
Meter=String
MeterStyle=MeterString

[MeterString40-11]
Meter=String
MeterStyle=MeterString

[MeterString40-12]
Meter=String
MeterStyle=MeterString

[MeterString40-13]
Meter=String
MeterStyle=MeterString

[MeterString40-14]
Meter=String
MeterStyle=MeterString

[MeterString40-15]
Meter=String
MeterStyle=MeterString

[MeterString40-16]
Meter=String
MeterStyle=MeterString

[MeterString40-17]
Meter=String
MeterStyle=MeterString

[MeterString40-18]
Meter=String
MeterStyle=MeterString

[MeterString40-19]
Meter=String
MeterStyle=MeterString

[MeterString40-20]
Meter=String
MeterStyle=MeterString

[MeterString40-21]
Meter=String
MeterStyle=MeterString

[MeterString40-22]
Meter=String
MeterStyle=MeterString

[MeterString40-23]
Meter=String
MeterStyle=MeterString

[MeterString40-24]
Meter=String
MeterStyle=MeterString