[MeterString37-1]
Meter=String
MeterStyle=MeterString

[MeterString37-2]
Meter=String
MeterStyle=MeterString

[MeterString37-3]
Meter=String
MeterStyle=MeterString

[MeterString37-4]
Meter=String
MeterStyle=MeterString

[MeterString37-5]
Meter=String
MeterStyle=MeterString

[MeterString37-6]
Meter=String
MeterStyle=MeterString

[MeterString37-7]
Meter=String
MeterStyle=MeterString

[MeterString37-8]
Meter=String
MeterStyle=MeterString

[MeterString37-9]
Meter=String
MeterStyle=MeterString

[MeterString37-10]
Meter=String
MeterStyle=MeterString

[MeterString37-11]
Meter=String
MeterStyle=MeterString

[MeterString37-12]
Meter=String
MeterStyle=MeterString

[MeterString37-13]
Meter=String
MeterStyle=MeterString

[MeterString37-14]
Meter=String
MeterStyle=MeterString

[MeterString37-15]
Meter=String
MeterStyle=MeterString

[MeterString37-16]
Meter=String
MeterStyle=MeterString

[MeterString37-17]
Meter=String
MeterStyle=MeterString

[MeterString37-18]
Meter=String
MeterStyle=MeterString

[MeterString37-19]
Meter=String
MeterStyle=MeterString

[MeterString37-20]
Meter=String
MeterStyle=MeterString

[MeterString37-21]
Meter=String
MeterStyle=MeterString

[MeterString37-22]
Meter=String
MeterStyle=MeterString

[MeterString37-23]
Meter=String
MeterStyle=MeterString

[MeterString37-24]
Meter=String
MeterStyle=MeterString