[MeterString3-1]
Meter=String
MeterStyle=MeterString

[MeterString3-2]
Meter=String
MeterStyle=MeterString

[MeterString3-3]
Meter=String
MeterStyle=MeterString

[MeterString3-4]
Meter=String
MeterStyle=MeterString

[MeterString3-5]
Meter=String
MeterStyle=MeterString

[MeterString3-6]
Meter=String
MeterStyle=MeterString

[MeterString3-7]
Meter=String
MeterStyle=MeterString

[MeterString3-8]
Meter=String
MeterStyle=MeterString

[MeterString3-9]
Meter=String
MeterStyle=MeterString

[MeterString3-10]
Meter=String
MeterStyle=MeterString

[MeterString3-11]
Meter=String
MeterStyle=MeterString

[MeterString3-12]
Meter=String
MeterStyle=MeterString

[MeterString3-13]
Meter=String
MeterStyle=MeterString

[MeterString3-14]
Meter=String
MeterStyle=MeterString

[MeterString3-15]
Meter=String
MeterStyle=MeterString

[MeterString3-16]
Meter=String
MeterStyle=MeterString

[MeterString3-17]
Meter=String
MeterStyle=MeterString

[MeterString3-18]
Meter=String
MeterStyle=MeterString

[MeterString3-19]
Meter=String
MeterStyle=MeterString

[MeterString3-20]
Meter=String
MeterStyle=MeterString

[MeterString3-21]
Meter=String
MeterStyle=MeterString

[MeterString3-22]
Meter=String
MeterStyle=MeterString

[MeterString3-23]
Meter=String
MeterStyle=MeterString

[MeterString3-24]
Meter=String
MeterStyle=MeterString