[MeterString14-1]
Meter=String
MeterStyle=MeterString

[MeterString14-2]
Meter=String
MeterStyle=MeterString

[MeterString14-3]
Meter=String
MeterStyle=MeterString

[MeterString14-4]
Meter=String
MeterStyle=MeterString

[MeterString14-5]
Meter=String
MeterStyle=MeterString

[MeterString14-6]
Meter=String
MeterStyle=MeterString

[MeterString14-7]
Meter=String
MeterStyle=MeterString

[MeterString14-8]
Meter=String
MeterStyle=MeterString

[MeterString14-9]
Meter=String
MeterStyle=MeterString

[MeterString14-10]
Meter=String
MeterStyle=MeterString

[MeterString14-11]
Meter=String
MeterStyle=MeterString

[MeterString14-12]
Meter=String
MeterStyle=MeterString

[MeterString14-13]
Meter=String
MeterStyle=MeterString

[MeterString14-14]
Meter=String
MeterStyle=MeterString

[MeterString14-15]
Meter=String
MeterStyle=MeterString

[MeterString14-16]
Meter=String
MeterStyle=MeterString

[MeterString14-17]
Meter=String
MeterStyle=MeterString

[MeterString14-18]
Meter=String
MeterStyle=MeterString

[MeterString14-19]
Meter=String
MeterStyle=MeterString

[MeterString14-20]
Meter=String
MeterStyle=MeterString

[MeterString14-21]
Meter=String
MeterStyle=MeterString

[MeterString14-22]
Meter=String
MeterStyle=MeterString

[MeterString14-23]
Meter=String
MeterStyle=MeterString

[MeterString14-24]
Meter=String
MeterStyle=MeterString