[MeterString29-1]
Meter=String
MeterStyle=MeterString

[MeterString29-2]
Meter=String
MeterStyle=MeterString

[MeterString29-3]
Meter=String
MeterStyle=MeterString

[MeterString29-4]
Meter=String
MeterStyle=MeterString

[MeterString29-5]
Meter=String
MeterStyle=MeterString

[MeterString29-6]
Meter=String
MeterStyle=MeterString

[MeterString29-7]
Meter=String
MeterStyle=MeterString

[MeterString29-8]
Meter=String
MeterStyle=MeterString

[MeterString29-9]
Meter=String
MeterStyle=MeterString

[MeterString29-10]
Meter=String
MeterStyle=MeterString

[MeterString29-11]
Meter=String
MeterStyle=MeterString

[MeterString29-12]
Meter=String
MeterStyle=MeterString

[MeterString29-13]
Meter=String
MeterStyle=MeterString

[MeterString29-14]
Meter=String
MeterStyle=MeterString

[MeterString29-15]
Meter=String
MeterStyle=MeterString

[MeterString29-16]
Meter=String
MeterStyle=MeterString

[MeterString29-17]
Meter=String
MeterStyle=MeterString

[MeterString29-18]
Meter=String
MeterStyle=MeterString

[MeterString29-19]
Meter=String
MeterStyle=MeterString

[MeterString29-20]
Meter=String
MeterStyle=MeterString

[MeterString29-21]
Meter=String
MeterStyle=MeterString

[MeterString29-22]
Meter=String
MeterStyle=MeterString

[MeterString29-23]
Meter=String
MeterStyle=MeterString

[MeterString29-24]
Meter=String
MeterStyle=MeterString