[MeterString10-1]
Meter=String
MeterStyle=MeterString

[MeterString10-2]
Meter=String
MeterStyle=MeterString

[MeterString10-3]
Meter=String
MeterStyle=MeterString

[MeterString10-4]
Meter=String
MeterStyle=MeterString

[MeterString10-5]
Meter=String
MeterStyle=MeterString

[MeterString10-6]
Meter=String
MeterStyle=MeterString

[MeterString10-7]
Meter=String
MeterStyle=MeterString

[MeterString10-8]
Meter=String
MeterStyle=MeterString

[MeterString10-9]
Meter=String
MeterStyle=MeterString

[MeterString10-10]
Meter=String
MeterStyle=MeterString

[MeterString10-11]
Meter=String
MeterStyle=MeterString

[MeterString10-12]
Meter=String
MeterStyle=MeterString

[MeterString10-13]
Meter=String
MeterStyle=MeterString

[MeterString10-14]
Meter=String
MeterStyle=MeterString

[MeterString10-15]
Meter=String
MeterStyle=MeterString

[MeterString10-16]
Meter=String
MeterStyle=MeterString

[MeterString10-17]
Meter=String
MeterStyle=MeterString

[MeterString10-18]
Meter=String
MeterStyle=MeterString

[MeterString10-19]
Meter=String
MeterStyle=MeterString

[MeterString10-20]
Meter=String
MeterStyle=MeterString

[MeterString10-21]
Meter=String
MeterStyle=MeterString

[MeterString10-22]
Meter=String
MeterStyle=MeterString

[MeterString10-23]
Meter=String
MeterStyle=MeterString

[MeterString10-24]
Meter=String
MeterStyle=MeterString