[MeterString38-1]
Meter=String
MeterStyle=MeterString

[MeterString38-2]
Meter=String
MeterStyle=MeterString

[MeterString38-3]
Meter=String
MeterStyle=MeterString

[MeterString38-4]
Meter=String
MeterStyle=MeterString

[MeterString38-5]
Meter=String
MeterStyle=MeterString

[MeterString38-6]
Meter=String
MeterStyle=MeterString

[MeterString38-7]
Meter=String
MeterStyle=MeterString

[MeterString38-8]
Meter=String
MeterStyle=MeterString

[MeterString38-9]
Meter=String
MeterStyle=MeterString

[MeterString38-10]
Meter=String
MeterStyle=MeterString

[MeterString38-11]
Meter=String
MeterStyle=MeterString

[MeterString38-12]
Meter=String
MeterStyle=MeterString

[MeterString38-13]
Meter=String
MeterStyle=MeterString

[MeterString38-14]
Meter=String
MeterStyle=MeterString

[MeterString38-15]
Meter=String
MeterStyle=MeterString

[MeterString38-16]
Meter=String
MeterStyle=MeterString

[MeterString38-17]
Meter=String
MeterStyle=MeterString

[MeterString38-18]
Meter=String
MeterStyle=MeterString

[MeterString38-19]
Meter=String
MeterStyle=MeterString

[MeterString38-20]
Meter=String
MeterStyle=MeterString

[MeterString38-21]
Meter=String
MeterStyle=MeterString

[MeterString38-22]
Meter=String
MeterStyle=MeterString

[MeterString38-23]
Meter=String
MeterStyle=MeterString

[MeterString38-24]
Meter=String
MeterStyle=MeterString