[MeterString22-1]
Meter=String
MeterStyle=MeterString

[MeterString22-2]
Meter=String
MeterStyle=MeterString

[MeterString22-3]
Meter=String
MeterStyle=MeterString

[MeterString22-4]
Meter=String
MeterStyle=MeterString

[MeterString22-5]
Meter=String
MeterStyle=MeterString

[MeterString22-6]
Meter=String
MeterStyle=MeterString

[MeterString22-7]
Meter=String
MeterStyle=MeterString

[MeterString22-8]
Meter=String
MeterStyle=MeterString

[MeterString22-9]
Meter=String
MeterStyle=MeterString

[MeterString22-10]
Meter=String
MeterStyle=MeterString

[MeterString22-11]
Meter=String
MeterStyle=MeterString

[MeterString22-12]
Meter=String
MeterStyle=MeterString

[MeterString22-13]
Meter=String
MeterStyle=MeterString

[MeterString22-14]
Meter=String
MeterStyle=MeterString

[MeterString22-15]
Meter=String
MeterStyle=MeterString

[MeterString22-16]
Meter=String
MeterStyle=MeterString

[MeterString22-17]
Meter=String
MeterStyle=MeterString

[MeterString22-18]
Meter=String
MeterStyle=MeterString

[MeterString22-19]
Meter=String
MeterStyle=MeterString

[MeterString22-20]
Meter=String
MeterStyle=MeterString

[MeterString22-21]
Meter=String
MeterStyle=MeterString

[MeterString22-22]
Meter=String
MeterStyle=MeterString

[MeterString22-23]
Meter=String
MeterStyle=MeterString

[MeterString22-24]
Meter=String
MeterStyle=MeterString