[MeterString42-1]
Meter=String
MeterStyle=MeterString

[MeterString42-2]
Meter=String
MeterStyle=MeterString

[MeterString42-3]
Meter=String
MeterStyle=MeterString

[MeterString42-4]
Meter=String
MeterStyle=MeterString

[MeterString42-5]
Meter=String
MeterStyle=MeterString

[MeterString42-6]
Meter=String
MeterStyle=MeterString

[MeterString42-7]
Meter=String
MeterStyle=MeterString

[MeterString42-8]
Meter=String
MeterStyle=MeterString

[MeterString42-9]
Meter=String
MeterStyle=MeterString

[MeterString42-10]
Meter=String
MeterStyle=MeterString

[MeterString42-11]
Meter=String
MeterStyle=MeterString

[MeterString42-12]
Meter=String
MeterStyle=MeterString

[MeterString42-13]
Meter=String
MeterStyle=MeterString

[MeterString42-14]
Meter=String
MeterStyle=MeterString

[MeterString42-15]
Meter=String
MeterStyle=MeterString

[MeterString42-16]
Meter=String
MeterStyle=MeterString

[MeterString42-17]
Meter=String
MeterStyle=MeterString

[MeterString42-18]
Meter=String
MeterStyle=MeterString

[MeterString42-19]
Meter=String
MeterStyle=MeterString

[MeterString42-20]
Meter=String
MeterStyle=MeterString

[MeterString42-21]
Meter=String
MeterStyle=MeterString

[MeterString42-22]
Meter=String
MeterStyle=MeterString

[MeterString42-23]
Meter=String
MeterStyle=MeterString

[MeterString42-24]
Meter=String
MeterStyle=MeterString