[MeterString4-1]
Meter=String
MeterStyle=MeterString

[MeterString4-2]
Meter=String
MeterStyle=MeterString

[MeterString4-3]
Meter=String
MeterStyle=MeterString

[MeterString4-4]
Meter=String
MeterStyle=MeterString

[MeterString4-5]
Meter=String
MeterStyle=MeterString

[MeterString4-6]
Meter=String
MeterStyle=MeterString

[MeterString4-7]
Meter=String
MeterStyle=MeterString

[MeterString4-8]
Meter=String
MeterStyle=MeterString

[MeterString4-9]
Meter=String
MeterStyle=MeterString

[MeterString4-10]
Meter=String
MeterStyle=MeterString

[MeterString4-11]
Meter=String
MeterStyle=MeterString

[MeterString4-12]
Meter=String
MeterStyle=MeterString

[MeterString4-13]
Meter=String
MeterStyle=MeterString

[MeterString4-14]
Meter=String
MeterStyle=MeterString

[MeterString4-15]
Meter=String
MeterStyle=MeterString

[MeterString4-16]
Meter=String
MeterStyle=MeterString

[MeterString4-17]
Meter=String
MeterStyle=MeterString

[MeterString4-18]
Meter=String
MeterStyle=MeterString

[MeterString4-19]
Meter=String
MeterStyle=MeterString

[MeterString4-20]
Meter=String
MeterStyle=MeterString

[MeterString4-21]
Meter=String
MeterStyle=MeterString

[MeterString4-22]
Meter=String
MeterStyle=MeterString

[MeterString4-23]
Meter=String
MeterStyle=MeterString

[MeterString4-24]
Meter=String
MeterStyle=MeterString