[MeterString5-1]
Meter=String
MeterStyle=MeterString

[MeterString5-2]
Meter=String
MeterStyle=MeterString

[MeterString5-3]
Meter=String
MeterStyle=MeterString

[MeterString5-4]
Meter=String
MeterStyle=MeterString

[MeterString5-5]
Meter=String
MeterStyle=MeterString

[MeterString5-6]
Meter=String
MeterStyle=MeterString

[MeterString5-7]
Meter=String
MeterStyle=MeterString

[MeterString5-8]
Meter=String
MeterStyle=MeterString

[MeterString5-9]
Meter=String
MeterStyle=MeterString

[MeterString5-10]
Meter=String
MeterStyle=MeterString

[MeterString5-11]
Meter=String
MeterStyle=MeterString

[MeterString5-12]
Meter=String
MeterStyle=MeterString

[MeterString5-13]
Meter=String
MeterStyle=MeterString

[MeterString5-14]
Meter=String
MeterStyle=MeterString

[MeterString5-15]
Meter=String
MeterStyle=MeterString

[MeterString5-16]
Meter=String
MeterStyle=MeterString

[MeterString5-17]
Meter=String
MeterStyle=MeterString

[MeterString5-18]
Meter=String
MeterStyle=MeterString

[MeterString5-19]
Meter=String
MeterStyle=MeterString

[MeterString5-20]
Meter=String
MeterStyle=MeterString

[MeterString5-21]
Meter=String
MeterStyle=MeterString

[MeterString5-22]
Meter=String
MeterStyle=MeterString

[MeterString5-23]
Meter=String
MeterStyle=MeterString

[MeterString5-24]
Meter=String
MeterStyle=MeterString