[MeterString13-1]
Meter=String
MeterStyle=MeterString

[MeterString13-2]
Meter=String
MeterStyle=MeterString

[MeterString13-3]
Meter=String
MeterStyle=MeterString

[MeterString13-4]
Meter=String
MeterStyle=MeterString

[MeterString13-5]
Meter=String
MeterStyle=MeterString

[MeterString13-6]
Meter=String
MeterStyle=MeterString

[MeterString13-7]
Meter=String
MeterStyle=MeterString

[MeterString13-8]
Meter=String
MeterStyle=MeterString

[MeterString13-9]
Meter=String
MeterStyle=MeterString

[MeterString13-10]
Meter=String
MeterStyle=MeterString

[MeterString13-11]
Meter=String
MeterStyle=MeterString

[MeterString13-12]
Meter=String
MeterStyle=MeterString

[MeterString13-13]
Meter=String
MeterStyle=MeterString

[MeterString13-14]
Meter=String
MeterStyle=MeterString

[MeterString13-15]
Meter=String
MeterStyle=MeterString

[MeterString13-16]
Meter=String
MeterStyle=MeterString

[MeterString13-17]
Meter=String
MeterStyle=MeterString

[MeterString13-18]
Meter=String
MeterStyle=MeterString

[MeterString13-19]
Meter=String
MeterStyle=MeterString

[MeterString13-20]
Meter=String
MeterStyle=MeterString

[MeterString13-21]
Meter=String
MeterStyle=MeterString

[MeterString13-22]
Meter=String
MeterStyle=MeterString

[MeterString13-23]
Meter=String
MeterStyle=MeterString

[MeterString13-24]
Meter=String
MeterStyle=MeterString