[MeterString6-1]
Meter=String
MeterStyle=MeterString

[MeterString6-2]
Meter=String
MeterStyle=MeterString

[MeterString6-3]
Meter=String
MeterStyle=MeterString

[MeterString6-4]
Meter=String
MeterStyle=MeterString

[MeterString6-5]
Meter=String
MeterStyle=MeterString

[MeterString6-6]
Meter=String
MeterStyle=MeterString

[MeterString6-7]
Meter=String
MeterStyle=MeterString

[MeterString6-8]
Meter=String
MeterStyle=MeterString

[MeterString6-9]
Meter=String
MeterStyle=MeterString

[MeterString6-10]
Meter=String
MeterStyle=MeterString

[MeterString6-11]
Meter=String
MeterStyle=MeterString

[MeterString6-12]
Meter=String
MeterStyle=MeterString

[MeterString6-13]
Meter=String
MeterStyle=MeterString

[MeterString6-14]
Meter=String
MeterStyle=MeterString

[MeterString6-15]
Meter=String
MeterStyle=MeterString

[MeterString6-16]
Meter=String
MeterStyle=MeterString

[MeterString6-17]
Meter=String
MeterStyle=MeterString

[MeterString6-18]
Meter=String
MeterStyle=MeterString

[MeterString6-19]
Meter=String
MeterStyle=MeterString

[MeterString6-20]
Meter=String
MeterStyle=MeterString

[MeterString6-21]
Meter=String
MeterStyle=MeterString

[MeterString6-22]
Meter=String
MeterStyle=MeterString

[MeterString6-23]
Meter=String
MeterStyle=MeterString

[MeterString6-24]
Meter=String
MeterStyle=MeterString