[MeterString23-1]
Meter=String
MeterStyle=MeterString

[MeterString23-2]
Meter=String
MeterStyle=MeterString

[MeterString23-3]
Meter=String
MeterStyle=MeterString

[MeterString23-4]
Meter=String
MeterStyle=MeterString

[MeterString23-5]
Meter=String
MeterStyle=MeterString

[MeterString23-6]
Meter=String
MeterStyle=MeterString

[MeterString23-7]
Meter=String
MeterStyle=MeterString

[MeterString23-8]
Meter=String
MeterStyle=MeterString

[MeterString23-9]
Meter=String
MeterStyle=MeterString

[MeterString23-10]
Meter=String
MeterStyle=MeterString

[MeterString23-11]
Meter=String
MeterStyle=MeterString

[MeterString23-12]
Meter=String
MeterStyle=MeterString

[MeterString23-13]
Meter=String
MeterStyle=MeterString

[MeterString23-14]
Meter=String
MeterStyle=MeterString

[MeterString23-15]
Meter=String
MeterStyle=MeterString

[MeterString23-16]
Meter=String
MeterStyle=MeterString

[MeterString23-17]
Meter=String
MeterStyle=MeterString

[MeterString23-18]
Meter=String
MeterStyle=MeterString

[MeterString23-19]
Meter=String
MeterStyle=MeterString

[MeterString23-20]
Meter=String
MeterStyle=MeterString

[MeterString23-21]
Meter=String
MeterStyle=MeterString

[MeterString23-22]
Meter=String
MeterStyle=MeterString

[MeterString23-23]
Meter=String
MeterStyle=MeterString

[MeterString23-24]
Meter=String
MeterStyle=MeterString