[ScriptRepeatReadMeters1]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters1.inc
Sub=Repeat
Index=1
Limit=1

[ScriptRepeatWriteMeters1]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters1.inc
WriteFile=#@#WriteMeters1.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters1.inc

[MeterDummy1]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters2]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters2.inc
Sub=Repeat
Index=2
Limit=2

[ScriptRepeatWriteMeters2]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters2.inc
WriteFile=#@#WriteMeters2.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters2.inc

[MeterDummy2]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters3]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters3.inc
Sub=Repeat
Index=3
Limit=3

[ScriptRepeatWriteMeters3]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters3.inc
WriteFile=#@#WriteMeters3.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters3.inc

[MeterDummy3]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters4]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters4.inc
Sub=Repeat
Index=4
Limit=4

[ScriptRepeatWriteMeters4]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters4.inc
WriteFile=#@#WriteMeters4.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters4.inc

[MeterDummy4]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters5]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters5.inc
Sub=Repeat
Index=5
Limit=5

[ScriptRepeatWriteMeters5]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters5.inc
WriteFile=#@#WriteMeters5.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters5.inc

[MeterDummy5]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters6]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters6.inc
Sub=Repeat
Index=6
Limit=6

[ScriptRepeatWriteMeters6]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters6.inc
WriteFile=#@#WriteMeters6.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters6.inc

[MeterDummy6]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters7]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters7.inc
Sub=Repeat
Index=7
Limit=7

[ScriptRepeatWriteMeters7]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters7.inc
WriteFile=#@#WriteMeters7.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters7.inc

[MeterDummy7]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters8]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters8.inc
Sub=Repeat
Index=8
Limit=8

[ScriptRepeatWriteMeters8]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters8.inc
WriteFile=#@#WriteMeters8.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters8.inc

[MeterDummy8]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters9]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters9.inc
Sub=Repeat
Index=9
Limit=9

[ScriptRepeatWriteMeters9]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters9.inc
WriteFile=#@#WriteMeters9.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters9.inc

[MeterDummy9]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters10]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters10.inc
Sub=Repeat
Index=10
Limit=10

[ScriptRepeatWriteMeters10]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters10.inc
WriteFile=#@#WriteMeters10.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters10.inc

[MeterDummy10]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters11]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters11.inc
Sub=Repeat
Index=11
Limit=11

[ScriptRepeatWriteMeters11]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters11.inc
WriteFile=#@#WriteMeters11.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters11.inc

[MeterDummy11]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters12]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters12.inc
Sub=Repeat
Index=12
Limit=12

[ScriptRepeatWriteMeters12]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters12.inc
WriteFile=#@#WriteMeters12.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters12.inc

[MeterDummy12]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters13]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters13.inc
Sub=Repeat
Index=13
Limit=13

[ScriptRepeatWriteMeters13]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters13.inc
WriteFile=#@#WriteMeters13.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters13.inc

[MeterDummy13]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters14]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters14.inc
Sub=Repeat
Index=14
Limit=14

[ScriptRepeatWriteMeters14]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters14.inc
WriteFile=#@#WriteMeters14.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters14.inc

[MeterDummy14]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters15]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters15.inc
Sub=Repeat
Index=15
Limit=15

[ScriptRepeatWriteMeters15]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters15.inc
WriteFile=#@#WriteMeters15.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters15.inc

[MeterDummy15]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters16]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters16.inc
Sub=Repeat
Index=16
Limit=16

[ScriptRepeatWriteMeters16]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters16.inc
WriteFile=#@#WriteMeters16.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters16.inc

[MeterDummy16]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters17]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters17.inc
Sub=Repeat
Index=17
Limit=17

[ScriptRepeatWriteMeters17]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters17.inc
WriteFile=#@#WriteMeters17.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters17.inc

[MeterDummy17]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters18]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters18.inc
Sub=Repeat
Index=18
Limit=18

[ScriptRepeatWriteMeters18]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters18.inc
WriteFile=#@#WriteMeters18.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters18.inc

[MeterDummy18]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters19]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters19.inc
Sub=Repeat
Index=19
Limit=19

[ScriptRepeatWriteMeters19]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters19.inc
WriteFile=#@#WriteMeters19.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters19.inc

[MeterDummy19]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters20]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters20.inc
Sub=Repeat
Index=20
Limit=20

[ScriptRepeatWriteMeters20]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters20.inc
WriteFile=#@#WriteMeters20.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters20.inc

[MeterDummy20]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters21]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters21.inc
Sub=Repeat
Index=21
Limit=21

[ScriptRepeatWriteMeters21]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters21.inc
WriteFile=#@#WriteMeters21.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters21.inc

[MeterDummy21]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters22]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters22.inc
Sub=Repeat
Index=22
Limit=22

[ScriptRepeatWriteMeters22]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters22.inc
WriteFile=#@#WriteMeters22.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters22.inc

[MeterDummy22]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters23]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters23.inc
Sub=Repeat
Index=23
Limit=23

[ScriptRepeatWriteMeters23]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters23.inc
WriteFile=#@#WriteMeters23.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters23.inc

[MeterDummy23]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters24]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters24.inc
Sub=Repeat
Index=24
Limit=24

[ScriptRepeatWriteMeters24]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters24.inc
WriteFile=#@#WriteMeters24.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters24.inc

[MeterDummy24]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters25]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters25.inc
Sub=Repeat
Index=25
Limit=25

[ScriptRepeatWriteMeters25]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters25.inc
WriteFile=#@#WriteMeters25.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters25.inc

[MeterDummy25]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters26]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters26.inc
Sub=Repeat
Index=26
Limit=26

[ScriptRepeatWriteMeters26]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters26.inc
WriteFile=#@#WriteMeters26.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters26.inc

[MeterDummy26]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters27]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters27.inc
Sub=Repeat
Index=27
Limit=27

[ScriptRepeatWriteMeters27]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters27.inc
WriteFile=#@#WriteMeters27.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters27.inc

[MeterDummy27]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters28]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters28.inc
Sub=Repeat
Index=28
Limit=28

[ScriptRepeatWriteMeters28]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters28.inc
WriteFile=#@#WriteMeters28.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters28.inc

[MeterDummy28]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters29]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters29.inc
Sub=Repeat
Index=29
Limit=29

[ScriptRepeatWriteMeters29]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters29.inc
WriteFile=#@#WriteMeters29.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters29.inc

[MeterDummy29]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters30]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters30.inc
Sub=Repeat
Index=30
Limit=30

[ScriptRepeatWriteMeters30]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters30.inc
WriteFile=#@#WriteMeters30.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters30.inc

[MeterDummy30]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters31]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters31.inc
Sub=Repeat
Index=31
Limit=31

[ScriptRepeatWriteMeters31]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters31.inc
WriteFile=#@#WriteMeters31.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters31.inc

[MeterDummy31]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters32]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters32.inc
Sub=Repeat
Index=32
Limit=32

[ScriptRepeatWriteMeters32]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters32.inc
WriteFile=#@#WriteMeters32.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters32.inc

[MeterDummy32]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters33]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters33.inc
Sub=Repeat
Index=33
Limit=33

[ScriptRepeatWriteMeters33]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters33.inc
WriteFile=#@#WriteMeters33.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters33.inc

[MeterDummy33]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters34]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters34.inc
Sub=Repeat
Index=34
Limit=34

[ScriptRepeatWriteMeters34]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters34.inc
WriteFile=#@#WriteMeters34.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters34.inc

[MeterDummy34]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters35]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters35.inc
Sub=Repeat
Index=35
Limit=35

[ScriptRepeatWriteMeters35]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters35.inc
WriteFile=#@#WriteMeters35.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters35.inc

[MeterDummy35]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters36]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters36.inc
Sub=Repeat
Index=36
Limit=36

[ScriptRepeatWriteMeters36]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters36.inc
WriteFile=#@#WriteMeters36.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters36.inc

[MeterDummy36]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters37]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters37.inc
Sub=Repeat
Index=37
Limit=37

[ScriptRepeatWriteMeters37]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters37.inc
WriteFile=#@#WriteMeters37.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters37.inc

[MeterDummy37]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters38]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters38.inc
Sub=Repeat
Index=38
Limit=38

[ScriptRepeatWriteMeters38]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters38.inc
WriteFile=#@#WriteMeters38.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters38.inc

[MeterDummy38]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters39]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters39.inc
Sub=Repeat
Index=39
Limit=39

[ScriptRepeatWriteMeters39]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters39.inc
WriteFile=#@#WriteMeters39.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters39.inc

[MeterDummy39]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters40]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters40.inc
Sub=Repeat
Index=40
Limit=40

[ScriptRepeatWriteMeters40]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters40.inc
WriteFile=#@#WriteMeters40.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters40.inc

[MeterDummy40]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters41]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters41.inc
Sub=Repeat
Index=41
Limit=41

[ScriptRepeatWriteMeters41]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters41.inc
WriteFile=#@#WriteMeters41.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters41.inc

[MeterDummy41]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters42]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters42.inc
Sub=Repeat
Index=42
Limit=42

[ScriptRepeatWriteMeters42]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters42.inc
WriteFile=#@#WriteMeters42.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters42.inc

[MeterDummy42]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters43]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters43.inc
Sub=Repeat
Index=43
Limit=43

[ScriptRepeatWriteMeters43]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters43.inc
WriteFile=#@#WriteMeters43.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters43.inc

[MeterDummy43]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters44]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters44.inc
Sub=Repeat
Index=44
Limit=44

[ScriptRepeatWriteMeters44]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters44.inc
WriteFile=#@#WriteMeters44.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters44.inc

[MeterDummy44]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters45]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters45.inc
Sub=Repeat
Index=45
Limit=45

[ScriptRepeatWriteMeters45]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters45.inc
WriteFile=#@#WriteMeters45.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters45.inc

[MeterDummy45]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters46]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters46.inc
Sub=Repeat
Index=46
Limit=46

[ScriptRepeatWriteMeters46]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters46.inc
WriteFile=#@#WriteMeters46.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters46.inc

[MeterDummy46]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1

[ScriptRepeatReadMeters47]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters.inc
WriteFile=#@#ReadMeters47.inc
Sub=Repeat
Index=47
Limit=47

[ScriptRepeatWriteMeters47]
Measure=Script
ScriptFile=#@#RepeatSection.lua
ReadFile=#@#ReadMeters47.inc
WriteFile=#@#WriteMeters47.inc
Sub=#
Index=1
Limit=#Levels#
@Include=#@#WriteMeters47.inc

[MeterDummy47]
Meter=Bar
MeasureName=MeasureAudio
X=0R
UpdateDivider=-1