[MeterString1-1]
Meter=String
MeterStyle=MeterString

[MeterString1-2]
Meter=String
MeterStyle=MeterString

[MeterString1-3]
Meter=String
MeterStyle=MeterString

[MeterString1-4]
Meter=String
MeterStyle=MeterString

[MeterString1-5]
Meter=String
MeterStyle=MeterString

[MeterString1-6]
Meter=String
MeterStyle=MeterString

[MeterString1-7]
Meter=String
MeterStyle=MeterString

[MeterString1-8]
Meter=String
MeterStyle=MeterString

[MeterString1-9]
Meter=String
MeterStyle=MeterString

[MeterString1-10]
Meter=String
MeterStyle=MeterString

[MeterString1-11]
Meter=String
MeterStyle=MeterString

[MeterString1-12]
Meter=String
MeterStyle=MeterString

[MeterString1-13]
Meter=String
MeterStyle=MeterString

[MeterString1-14]
Meter=String
MeterStyle=MeterString

[MeterString1-15]
Meter=String
MeterStyle=MeterString

[MeterString1-16]
Meter=String
MeterStyle=MeterString

[MeterString1-17]
Meter=String
MeterStyle=MeterString

[MeterString1-18]
Meter=String
MeterStyle=MeterString

[MeterString1-19]
Meter=String
MeterStyle=MeterString

[MeterString1-20]
Meter=String
MeterStyle=MeterString

[MeterString1-21]
Meter=String
MeterStyle=MeterString

[MeterString1-22]
Meter=String
MeterStyle=MeterString

[MeterString1-23]
Meter=String
MeterStyle=MeterString

[MeterString1-24]
Meter=String
MeterStyle=MeterString