[MeterString30-1]
Meter=String
MeterStyle=MeterString

[MeterString30-2]
Meter=String
MeterStyle=MeterString

[MeterString30-3]
Meter=String
MeterStyle=MeterString

[MeterString30-4]
Meter=String
MeterStyle=MeterString

[MeterString30-5]
Meter=String
MeterStyle=MeterString

[MeterString30-6]
Meter=String
MeterStyle=MeterString

[MeterString30-7]
Meter=String
MeterStyle=MeterString

[MeterString30-8]
Meter=String
MeterStyle=MeterString

[MeterString30-9]
Meter=String
MeterStyle=MeterString

[MeterString30-10]
Meter=String
MeterStyle=MeterString

[MeterString30-11]
Meter=String
MeterStyle=MeterString

[MeterString30-12]
Meter=String
MeterStyle=MeterString

[MeterString30-13]
Meter=String
MeterStyle=MeterString

[MeterString30-14]
Meter=String
MeterStyle=MeterString

[MeterString30-15]
Meter=String
MeterStyle=MeterString

[MeterString30-16]
Meter=String
MeterStyle=MeterString

[MeterString30-17]
Meter=String
MeterStyle=MeterString

[MeterString30-18]
Meter=String
MeterStyle=MeterString

[MeterString30-19]
Meter=String
MeterStyle=MeterString

[MeterString30-20]
Meter=String
MeterStyle=MeterString

[MeterString30-21]
Meter=String
MeterStyle=MeterString

[MeterString30-22]
Meter=String
MeterStyle=MeterString

[MeterString30-23]
Meter=String
MeterStyle=MeterString

[MeterString30-24]
Meter=String
MeterStyle=MeterString