[MeterString46-1]
Meter=String
MeterStyle=MeterString

[MeterString46-2]
Meter=String
MeterStyle=MeterString

[MeterString46-3]
Meter=String
MeterStyle=MeterString

[MeterString46-4]
Meter=String
MeterStyle=MeterString

[MeterString46-5]
Meter=String
MeterStyle=MeterString

[MeterString46-6]
Meter=String
MeterStyle=MeterString

[MeterString46-7]
Meter=String
MeterStyle=MeterString

[MeterString46-8]
Meter=String
MeterStyle=MeterString

[MeterString46-9]
Meter=String
MeterStyle=MeterString

[MeterString46-10]
Meter=String
MeterStyle=MeterString

[MeterString46-11]
Meter=String
MeterStyle=MeterString

[MeterString46-12]
Meter=String
MeterStyle=MeterString

[MeterString46-13]
Meter=String
MeterStyle=MeterString

[MeterString46-14]
Meter=String
MeterStyle=MeterString

[MeterString46-15]
Meter=String
MeterStyle=MeterString

[MeterString46-16]
Meter=String
MeterStyle=MeterString

[MeterString46-17]
Meter=String
MeterStyle=MeterString

[MeterString46-18]
Meter=String
MeterStyle=MeterString

[MeterString46-19]
Meter=String
MeterStyle=MeterString

[MeterString46-20]
Meter=String
MeterStyle=MeterString

[MeterString46-21]
Meter=String
MeterStyle=MeterString

[MeterString46-22]
Meter=String
MeterStyle=MeterString

[MeterString46-23]
Meter=String
MeterStyle=MeterString

[MeterString46-24]
Meter=String
MeterStyle=MeterString