[MeterString45-1]
Meter=String
MeterStyle=MeterString

[MeterString45-2]
Meter=String
MeterStyle=MeterString

[MeterString45-3]
Meter=String
MeterStyle=MeterString

[MeterString45-4]
Meter=String
MeterStyle=MeterString

[MeterString45-5]
Meter=String
MeterStyle=MeterString

[MeterString45-6]
Meter=String
MeterStyle=MeterString

[MeterString45-7]
Meter=String
MeterStyle=MeterString

[MeterString45-8]
Meter=String
MeterStyle=MeterString

[MeterString45-9]
Meter=String
MeterStyle=MeterString

[MeterString45-10]
Meter=String
MeterStyle=MeterString

[MeterString45-11]
Meter=String
MeterStyle=MeterString

[MeterString45-12]
Meter=String
MeterStyle=MeterString

[MeterString45-13]
Meter=String
MeterStyle=MeterString

[MeterString45-14]
Meter=String
MeterStyle=MeterString

[MeterString45-15]
Meter=String
MeterStyle=MeterString

[MeterString45-16]
Meter=String
MeterStyle=MeterString

[MeterString45-17]
Meter=String
MeterStyle=MeterString

[MeterString45-18]
Meter=String
MeterStyle=MeterString

[MeterString45-19]
Meter=String
MeterStyle=MeterString

[MeterString45-20]
Meter=String
MeterStyle=MeterString

[MeterString45-21]
Meter=String
MeterStyle=MeterString

[MeterString45-22]
Meter=String
MeterStyle=MeterString

[MeterString45-23]
Meter=String
MeterStyle=MeterString

[MeterString45-24]
Meter=String
MeterStyle=MeterString