[MeterString41-1]
Meter=String
MeterStyle=MeterString

[MeterString41-2]
Meter=String
MeterStyle=MeterString

[MeterString41-3]
Meter=String
MeterStyle=MeterString

[MeterString41-4]
Meter=String
MeterStyle=MeterString

[MeterString41-5]
Meter=String
MeterStyle=MeterString

[MeterString41-6]
Meter=String
MeterStyle=MeterString

[MeterString41-7]
Meter=String
MeterStyle=MeterString

[MeterString41-8]
Meter=String
MeterStyle=MeterString

[MeterString41-9]
Meter=String
MeterStyle=MeterString

[MeterString41-10]
Meter=String
MeterStyle=MeterString

[MeterString41-11]
Meter=String
MeterStyle=MeterString

[MeterString41-12]
Meter=String
MeterStyle=MeterString

[MeterString41-13]
Meter=String
MeterStyle=MeterString

[MeterString41-14]
Meter=String
MeterStyle=MeterString

[MeterString41-15]
Meter=String
MeterStyle=MeterString

[MeterString41-16]
Meter=String
MeterStyle=MeterString

[MeterString41-17]
Meter=String
MeterStyle=MeterString

[MeterString41-18]
Meter=String
MeterStyle=MeterString

[MeterString41-19]
Meter=String
MeterStyle=MeterString

[MeterString41-20]
Meter=String
MeterStyle=MeterString

[MeterString41-21]
Meter=String
MeterStyle=MeterString

[MeterString41-22]
Meter=String
MeterStyle=MeterString

[MeterString41-23]
Meter=String
MeterStyle=MeterString

[MeterString41-24]
Meter=String
MeterStyle=MeterString