[MeterString7-1]
Meter=String
MeterStyle=MeterString

[MeterString7-2]
Meter=String
MeterStyle=MeterString

[MeterString7-3]
Meter=String
MeterStyle=MeterString

[MeterString7-4]
Meter=String
MeterStyle=MeterString

[MeterString7-5]
Meter=String
MeterStyle=MeterString

[MeterString7-6]
Meter=String
MeterStyle=MeterString

[MeterString7-7]
Meter=String
MeterStyle=MeterString

[MeterString7-8]
Meter=String
MeterStyle=MeterString

[MeterString7-9]
Meter=String
MeterStyle=MeterString

[MeterString7-10]
Meter=String
MeterStyle=MeterString

[MeterString7-11]
Meter=String
MeterStyle=MeterString

[MeterString7-12]
Meter=String
MeterStyle=MeterString

[MeterString7-13]
Meter=String
MeterStyle=MeterString

[MeterString7-14]
Meter=String
MeterStyle=MeterString

[MeterString7-15]
Meter=String
MeterStyle=MeterString

[MeterString7-16]
Meter=String
MeterStyle=MeterString

[MeterString7-17]
Meter=String
MeterStyle=MeterString

[MeterString7-18]
Meter=String
MeterStyle=MeterString

[MeterString7-19]
Meter=String
MeterStyle=MeterString

[MeterString7-20]
Meter=String
MeterStyle=MeterString

[MeterString7-21]
Meter=String
MeterStyle=MeterString

[MeterString7-22]
Meter=String
MeterStyle=MeterString

[MeterString7-23]
Meter=String
MeterStyle=MeterString

[MeterString7-24]
Meter=String
MeterStyle=MeterString