[MeterString32-1]
Meter=String
MeterStyle=MeterString

[MeterString32-2]
Meter=String
MeterStyle=MeterString

[MeterString32-3]
Meter=String
MeterStyle=MeterString

[MeterString32-4]
Meter=String
MeterStyle=MeterString

[MeterString32-5]
Meter=String
MeterStyle=MeterString

[MeterString32-6]
Meter=String
MeterStyle=MeterString

[MeterString32-7]
Meter=String
MeterStyle=MeterString

[MeterString32-8]
Meter=String
MeterStyle=MeterString

[MeterString32-9]
Meter=String
MeterStyle=MeterString

[MeterString32-10]
Meter=String
MeterStyle=MeterString

[MeterString32-11]
Meter=String
MeterStyle=MeterString

[MeterString32-12]
Meter=String
MeterStyle=MeterString

[MeterString32-13]
Meter=String
MeterStyle=MeterString

[MeterString32-14]
Meter=String
MeterStyle=MeterString

[MeterString32-15]
Meter=String
MeterStyle=MeterString

[MeterString32-16]
Meter=String
MeterStyle=MeterString

[MeterString32-17]
Meter=String
MeterStyle=MeterString

[MeterString32-18]
Meter=String
MeterStyle=MeterString

[MeterString32-19]
Meter=String
MeterStyle=MeterString

[MeterString32-20]
Meter=String
MeterStyle=MeterString

[MeterString32-21]
Meter=String
MeterStyle=MeterString

[MeterString32-22]
Meter=String
MeterStyle=MeterString

[MeterString32-23]
Meter=String
MeterStyle=MeterString

[MeterString32-24]
Meter=String
MeterStyle=MeterString